PrototypeApp({
  name:'采协云 SRM',en:'SUPPLIER RELATIONSHIP',color:'#0f766e',color2:'#14b8a6',user:'周景行',role:'采购经理',badge:9,
  greeting:'采购工作台',subtitle:'洞察供应风险，让每一次寻源与交付清晰可控。',entity:'寻源项目',metricLabel:'采购金额',
  nav:['采购工作台','供应商库','准入管理','寻源管理','订单协同','质量管理','绩效与风险','报表中心','系统设置'],
  kpis:[{label:'活跃供应商',value:'248',trend:'↑ 6.8%'},{label:'进行中询价',value:'18',trend:'↑ 12.0%'},{label:'待确认订单',value:'26',trend:'↑ 4.2%'},{label:'延期订单',value:'7',trend:'↓ 16.7%'}],
  chartTitle:'采购金额与交付趋势',donutTitle:'供应商等级分布',focusTitle:'进行中寻源项目',categories:['A 级供应商','B 级供应商','C 级供应商'],
  rows:[{name:'控制器组件年度集采',code:'RFQ-202607-0068',status:'报价中',value:'¥ 1,280,000',progress:68,owner:'周景行'},{name:'华东仓储包装材料',code:'RFQ-202607-0062',status:'评审中',value:'¥ 560,000',progress:78,owner:'许清和'},{name:'精密轴承二次寻源',code:'RFQ-202606-0057',status:'定标审批',value:'¥ 860,000',progress:88,owner:'沈听澜'},{name:'办公设备框架采购',code:'RFQ-202606-0048',status:'待发布',value:'¥ 240,000',progress:32,owner:'周景行'},{name:'新能源电芯样品采购',code:'RFQ-202605-0039',status:'风险关注',value:'¥ 920,000',progress:41,owner:'许清和'}],
  activities:['控制器组件项目收到第 4 家供应商报价','华岳精工营业资质将在 15 天后到期','订单 PO-260701 创建第二批发货通知','质量工程师发起 NCR-2026-0032','精密轴承项目已提交定标审批'],
  pages:{
    1:{entity:'供应商',description:'供应商 360° 档案，覆盖品类、资质、订单、质量和绩效风险。',metricLabel:'综合等级',ownerLabel:'采购负责人',primaryAction:'新增供应商',codePrefix:'SUP',initialStatus:'待准入',activeStatus:'合作中',advanceAction:'调整合作状态',categories:['生产物料','服务采购','办公采购'],rows:[{name:'华岳精工有限公司',code:'SUP-000186',status:'合格',value:'A 级',progress:91,owner:'周景行'},{name:'海川电子科技',code:'SUP-000172',status:'观察',value:'B 级',progress:68,owner:'许清和'},{name:'东启包装材料',code:'SUP-000155',status:'资质将到期',value:'B 级',progress:54,owner:'沈听澜'}]},
    2:{entity:'准入申请',description:'供应商提交企业、资质、银行和品类资料，采购、质量、财务协同审核。',metricLabel:'资料完整度',ownerLabel:'审核负责人',primaryAction:'发起准入邀请',codePrefix:'ONB',initialStatus:'待填写',activeStatus:'审核中',reviewStatus:'终审中',advanceAction:'完成准入审核',categories:['新供应商','品类扩展','信息变更'],rows:[{name:'恒瑞传感器准入申请',code:'ONB-260708-028',status:'采购初审',value:'96%',progress:62,owner:'周景行'},{name:'智联物流服务准入',code:'ONB-260707-021',status:'质量审核',value:'88%',progress:74,owner:'沈听澜'},{name:'青禾办公用品准入',code:'ONB-260706-016',status:'补充资料',value:'72%',progress:45,owner:'许清和'}]},
    3:{kind:'kanban',entity:'询价项目',description:'创建 RFQ、邀请供应商、收集报价、开标比价与定标审批。',metricLabel:'预估金额',ownerLabel:'采购负责人',primaryAction:'创建询价项目',codePrefix:'RFQ',initialStatus:'草稿',activeStatus:'报价中',reviewStatus:'定标审批',advanceAction:'推进寻源阶段',categories:['公开询价','邀请询价','单一来源'],kanban:['草稿/待发布','报价与评审','定标审批'],rows:[{name:'控制器组件年度集采',code:'RFQ-202607-0068',status:'报价中',value:'¥ 1,280,000',progress:68,owner:'周景行'},{name:'华东仓储包装材料',code:'RFQ-202607-0062',status:'评审中',value:'¥ 560,000',progress:78,owner:'许清和'},{name:'精密轴承二次寻源',code:'RFQ-202606-0057',status:'定标审批',value:'¥ 860,000',progress:88,owner:'沈听澜'}]},
    4:{entity:'采购订单',description:'协同订单确认、交期变更、发货通知、收货和行项目差异。',metricLabel:'订单金额',ownerLabel:'采购员',progressLabel:'交付进度',primaryAction:'创建采购订单',codePrefix:'PO',initialStatus:'待确认',activeStatus:'交付中',reviewStatus:'待收货',advanceAction:'确认交付节点',categories:['生产订单','框架订单','服务订单'],rows:[{name:'控制器组件采购订单',code:'PO-260701-0188',status:'部分发货',value:'¥ 680,000',progress:58,owner:'周景行'},{name:'包装材料采购订单',code:'PO-260628-0162',status:'待确认',value:'¥ 240,000',progress:24,owner:'许清和'},{name:'精密轴承采购订单',code:'PO-260619-0141',status:'延期预警',value:'¥ 520,000',progress:71,owner:'沈听澜'}]},
    5:{entity:'质量单',description:'管理来料检验、不合格 NCR、原因分析、纠正措施与验证关闭。',metricLabel:'检验结果',ownerLabel:'质量工程师',primaryAction:'新建检验单',codePrefix:'IQC',initialStatus:'待检验',activeStatus:'整改中',reviewStatus:'验证中',advanceAction:'推进质量处理',categories:['来料检验','过程异常','供应商整改'],rows:[{name:'控制器批次来料检验',code:'IQC-260708-039',status:'待判定',value:'抽检 20 件',progress:52,owner:'沈听澜'},{name:'轴承尺寸不合格整改',code:'NCR-2026-0032',status:'措施待确认',value:'不良率 4.2%',progress:68,owner:'沈听澜'},{name:'包装破损异常验证',code:'NCR-2026-0028',status:'验证中',value:'不良率 1.8%',progress:86,owner:'顾言川'}]},
    6:{kind:'kanban',entity:'风险与绩效',description:'按质量、交付、价格、服务评估供应商，并闭环资质和交付风险。',metricLabel:'绩效分',ownerLabel:'品类经理',primaryAction:'发起绩效评估',codePrefix:'PERF',initialStatus:'待评估',activeStatus:'改进中',reviewStatus:'已复核',advanceAction:'确认绩效结果',categories:['质量绩效','交付绩效','综合风险'],kanban:['待评估','改进与观察','已复核'],rows:[{name:'华岳精工 Q2 绩效',code:'PERF-2026Q2-018',status:'A级建议',value:'92.4 分',progress:91,owner:'周景行'},{name:'海川电子交付改进',code:'RISK-260708-012',status:'改进中',value:'74.8 分',progress:58,owner:'许清和'},{name:'东启包装资质风险',code:'RISK-260707-009',status:'高风险',value:'68.2 分',progress:36,owner:'沈听澜'}]},
    7:{kind:'analytics',entity:'采购指标',description:'分析采购金额、品类支出、交付质量、寻源效率和供应商集中度。',metricLabel:'指标值',ownerLabel:'统计周期',chartTitle:'采购金额与节省趋势',donutTitle:'品类支出构成',categories:['生产物料','包装物流','间接采购'],kpis:[{label:'采购金额',value:'¥ 1,286万',trend:'↑ 6.8%'},{label:'节省率',value:'7.6%',trend:'↑ 1.2%'},{label:'准时交付率',value:'94.2%',trend:'↓ 0.8%'},{label:'质量合格率',value:'98.1%',trend:'↑ 0.5%'}],rows:[{name:'准时交付率',code:'KPI-OTD',status:'轻微偏低',value:'94.2%',progress:94,owner:'本月'},{name:'供应商质量合格率',code:'KPI-PPM',status:'正常',value:'98.1%',progress:98,owner:'本月'},{name:'寻源平均周期',code:'KPI-CYCLE',status:'持续改善',value:'8.4 天',progress:86,owner:'本季度'}]},
    8:{kind:'settings',entity:'SRM 配置',description:'配置品类、准入资质、评分权重、路由规则、组织角色与审计日志。',metricLabel:'当前配置',ownerLabel:'维护人',categories:['主数据','规则','权限'],rows:[{name:'供应商准入资质模板',code:'SET-QUAL',status:'已发布',value:'12 类资质',progress:100,owner:'采购运营'},{name:'绩效评分权重',code:'SET-SCORE',status:'已启用',value:'4 个维度',progress:100,owner:'采购经理'},{name:'寻源审批规则',code:'SET-APPROVAL',status:'待更新',value:'6 条规则',progress:72,owner:'系统管理员'},{name:'组织角色与数据权限',code:'SET-RBAC',status:'运行中',value:'4 个角色',progress:100,owner:'系统管理员'}]}
  },
  roles:[{name:'采购经理',user:'周景行',scope:'全部数据',nav:[0,1,2,3,4,5,6,7,8],permissions:['create','edit','export','advance']},{name:'采购专员',user:'许清和',scope:'个人数据',nav:[0,1,2,3,4,6,7],permissions:['create','edit','advance']},{name:'质量工程师',user:'沈听澜',scope:'质量相关数据',nav:[0,1,2,5,6],permissions:['edit','export','advance']},{name:'供应商业务员',user:'江屿',scope:'个人数据',nav:[0,3,4,5],permissions:['edit','advance']}]
});
